# Generated by Django 3.1.5 on 2021-01-17 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='plants',
        ),
        migrations.CreateModel(
            name='OrderPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plant')),
            ],
        ),
    ]
